# 视图的前辍与后辍
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp

  # 注册数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

  #编码设置
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  redis:
    host: 39.97.176.160
    port: 6379
  cache:
    type: redis   # 指定缓存类型
    cache-names: realTimeCache  # 指定缓存空间名称，随意


server:
  tomcat:
    uri-encoding: UTF-8

mybatis:
  # 注册映射文件
  mapper-locations: classpath:com/abc/dao/*.xml
  # 注册实体类别名
  type-aliases-package: com.abc.bean

      # 配置Redis高可用集群
      # sentinel:
      # master: mymaster
    # nodes: sentinelOS1:26379,sentinelOS2:26379,sentinelOS3:26379

